// <auto-generated />
namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v109 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v109));
        
        string IMigrationMetadata.Id
        {
            get { return "202010271125334_v1-0-9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
