// <auto-generated />
namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserMetadataV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMetadataV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202205101603006_UserMetadataV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
