// <auto-generated />
namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PageCommentsAndLikes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageCommentsAndLikes));
        
        string IMigrationMetadata.Id
        {
            get { return "202401191004335_PageCommentsAndLikes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
