// <auto-generated />

namespace Common.Entities.Migrations

{

    using System.CodeDom.Compiler;

    using System.Data.Entity.Migrations;

    using System.Data.Entity.Migrations.Infrastructure;

    using System.Resources;



    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]

    public sealed partial class LicenceHistory : IMigrationMetadata

    {

        private readonly ResourceManager Resources = new ResourceManager(typeof(LicenceHistory));



        string IMigrationMetadata.Id

        {

            get { return "202610021200001_LicenceHistory"; }

        }



        string IMigrationMetadata.Source

        {

            get { return null; }

        }



        string IMigrationMetadata.Target

        {

            get { return Resources.GetString("Target"); }

        }

    }

}
