// <auto-generated />

namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class Agent365PackageCatalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agent365PackageCatalog));

        string IMigrationMetadata.Id
        {
            get { return "202610071200001_Agent365PackageCatalog"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
