// <auto-generated />
namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PowerPlatformAuditLogging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PowerPlatformAuditLogging));
        
        string IMigrationMetadata.Id
        {
            get { return "202605141410030_PowerPlatformAuditLogging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
