// <auto-generated />
namespace Common.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1025));
        
        string IMigrationMetadata.Id
        {
            get { return "201803011140084_v1-0-25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
