//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///-- Create tables
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- Check to see if we see the expected number of columns
        ///if (SELECT count (*)  FROM INFORMATION_SCHEMA.COLUMNS 
        ///                 WHERE TABLE_SCHEMA = &apos;dbo&apos; 
        ///                 AND  TABLE_NAME = &apos;audit_events&apos;) = 5
        ///begin
        ///
        ///	print &apos;Upgraded already? Skipping schema modification &amp; migration&apos;
        ///end
        ///
        ///else
        ///begin
        ///
        ///	print &apos;Starting upgrade...&apos;
        ///
        ///	BEGIN TRY  
        ///	
        ///		--- Make sure we transaction everything
        ///		begin tran AuditUpgrade [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Audit_Log_Migration {
            get {
                return ResourceManager.GetString("Audit_Log_Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- --------------------------------------------------
        ///-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
        ///-- --------------------------------------------------
        ///-- Date Created: 12/09/2017 19:20:09
        ///-- Generated from EDMX file: C:\Users\sambetts\Source\Repos\SPOInsights VS Projects\Common.Entities\SPOInsightsActivityModel.edmx
        ///-- --------------------------------------------------
        ///
        ///SET QUOTED_IDENTIFIER OFF;
        ///GO
        ///
        ///IF SCHEMA_ID(N&apos;dbo&apos;) IS NULL EXECUTE(N&apos;CREATE SCHEMA [dbo]&apos;);
        ///GO
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_DB {
            get {
                return ResourceManager.GetString("Create_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @StartDate DATE, @NumberOfYears INT
        ///SET @StartDate = &apos;20180101&apos; 
        /// SET @NumberOfYears = 30;
        ///
        ///-- prevent set or regional settings from interfering with 
        ///-- interpretation of dates / literals
        ///
        ///SET DATEFIRST 7;
        ///SET DATEFORMAT mdy;
        ///--SET LANGUAGE UK_ENGLISH;
        ///
        ///DECLARE @CutoffDate DATE = DATEADD(YEAR, @NumberOfYears, @StartDate);
        ///
        ///If Object_ID(&apos;DimDate&apos;,&apos;u&apos;) IS NOT NULL
        ///BEGIN
        ///DROP Table DimDate
        ///END
        ///
        ///-- this is just a holding table for intermediate calculations:
        ///CREATE TABLE #dim
        ///(
        ///  [d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DimDate {
            get {
                return ResourceManager.GetString("Table_DimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[DimTime]    Script Date: 2020-01-19 18:07:08 ******/
        ///
        ///IF OBJECT_ID(&apos;dbo.dimTime&apos;,&apos;u&apos;) IS NOT NULL
        ///BEGIN
        ///DROP TABLE [dbo].[dimTime]
        ///END
        ///
        ///GO
        ////****** Object:  Table [dbo].[DimTime]    Script Date: 2020-01-19 18:07:08 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[DimTime](
        ///	[Time] [varchar](50) NOT NULL,
        ///	[Hour] [varchar](50) NOT NULL,
        ///	[Quarter Hour] [varchar](50) NOT NULL,
        ///	[Minute] [int] NOT NULL,
        ///	[Hour Number] [int] NOT NULL,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DimTime {
            get {
                return ResourceManager.GetString("Table_DimTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE OR ALTER VIEW [dbo].[vwTeamsCalls1] AS
        ///
        ///    WITH CTE AS (
        ///    SELECT call_session_id AS call_session_id,
        ///    MAX(CASE WHEN call_session_call_modalities.call_modality_id = 1 THEN &apos;Yes&apos; ELSE &apos;None&apos; END) AS Audio,
        ///    MAX(CASE WHEN call_session_call_modalities.call_modality_id = 2 THEN &apos;Yes&apos;ELSE &apos;None&apos; END) AS Video,
        ///    MAX(CASE WHEN call_session_call_modalities.call_modality_id = 3 THEN &apos;Yes&apos; ELSE &apos;None&apos; END) As VideoScreenShare,
        ///    MAX(CASE WHEN call_session_call_modalities.call_modality_id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsExtraViews1 {
            get {
                return ResourceManager.GetString("TeamsExtraViews1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[vwTeamsAddOns_Log]    Script Date: 27/10/2020 12:34:04 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///CREATE OR ALTER VIEW [dbo].[vwTeamsUsers] AS
        ///	SELECT teams_user_activity_log.user_id, teams_user_activity_log.meetings_count, teams_user_activity_log.private_chat_count, 
        ///		teams_user_activity_log.team_chat_count, teams_user_activity_log.calls_count,
        ///		dimdate.date, dimdate.WeekDayName AS dayName,  dimdate.MonthName, dimdate.Month AS monthNumber, 
        ///		dimD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsViewsV1 {
            get {
                return ResourceManager.GetString("TeamsViewsV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///
        ///CREATE OR ALTER VIEW [dbo].[vwTeamsDevices] AS
        ///SELECT 
        ///	   users.user_name
        ///      ,teams_user_device_usage_log.[used_web]
        ///      ,teams_user_device_usage_log.[used_win_phone]
        ///      ,teams_user_device_usage_log.[used_ios]
        ///      ,teams_user_device_usage_log.[used_android]
        ///      ,teams_user_device_usage_log.[used_mac]
        ///      ,teams_user_device_usage_log.[used_windows]
        ///	  ,dimdate.date
        ///	  ,dimdate.WeekDayName AS dayName
        ///	  ,dimdate.MonthName
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsViewsV2 {
            get {
                return ResourceManager.GetString("TeamsViewsV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[Content]    Script Date: 12/03/2020 15:47:28 ******/
        ///DROP VIEW if exists [dbo].[Content]
        ///GO
        ///
        ///
        ///CREATE VIEW [dbo].[Content] AS
        ///	SELECT audit_events.id
        ///			,[users].[user_name]
        ///			,[urls].full_url
        ///			,event_operations.operation_name as &apos;Event&apos;
        ///			,event_types.[type_name] AS &apos;Event Type&apos;
        ///			,event_file_ext.extension_name as &apos;File Type&apos;
        ///			,event_file_names.[file_name] as &apos;File Name&apos;
        ///			,CASE WHEN CHARINDEX(&apos;/sites/&apos;, webs.url_base) = 0 THEN URL_BASE ELSE SUBSTRING(webs.u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_Content {
            get {
                return ResourceManager.GetString("View_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[Usage]    Script Date: 12/03/2020 14:10:25 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///drop view if exists [dbo].[Usage]
        ///Go
        ///
        ///CREATE VIEW [dbo].[Usage] AS
        ///
        ///
        ///
        ///
        ///SELECT distinct hits.ID, hits.session_id, urls.full_url AS &apos;URL&apos;, browsers.browser_name AS &apos;Browser Name&apos;, provinces.province_name AS &apos;Region&apos;,users.user_Name AS &apos;User Name&apos;, page_titles.title AS &apos;Page Title&apos;, hits.seconds_on_page AS &apos;Seconds on Page&apos;,
        ///CASE WHEN devices.device_name = &apos;Laptop&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_Usage {
            get {
                return ResourceManager.GetString("View_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- ============================================
        ///-- Author: Glenn Pepper
        ///-- Create Date: 04/12/2019
        ///-- Version: 1.0
        ///-- Description: These view display event information
        ///-- =============================================
        ///
        ///IF OBJECT_ID(&apos;vwEvents&apos;,&apos;v&apos;) IS NOT NULL
        ///BEGIN
        ///DROP VIEW vwEvents
        ///END
        ///GO
        ///
        ///CREATE VIEW [dbo].[vwEvents] AS
        ///SELECT audit_events.id
        ///		,[user_id]
        ///		,[users].[user_name]
        ///		,url_id
        ///		,[urls].full_url
        ///		,operation_id
        ///		,event_operations.operation_name as operation
        ///		,item_type_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_vwEvents {
            get {
                return ResourceManager.GetString("View_vwEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- ============================================
        ///-- Author: Glenn Pepper
        ///-- Create Date: 04/12/2019
        ///-- Modified Date: 15/07/2020
        ///-- Version: 2.0
        ///-- Description: This view displays hit information
        ///-- Changes: Change column order, added a coalesce statement for NULLS in &apos;seconds_on_page&apos; column. 
        ///-- Index added to DimDate table to speed up query
        ///-- =============================================
        ///
        ///
        ///IF OBJECT_ID(&apos;vwHits_6Months&apos;,&apos;v&apos;) IS NOT NULL
        ///BEGIN
        ///DROP VIEW vwHits_6Months
        ///END
        ///GO
        ///
        ///CREATE VIEW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_VWHits {
            get {
                return ResourceManager.GetString("View_VWHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- ============================================
        ///-- Author: Glenn Pepper
        ///-- Create Date: 03/08/2020
        ///-- Version: 2.0
        ///-- Description: This view displays search information
        ///-- This was amended to include a view for Searches for past 6 months
        ///-- =============================================
        ///
        ///
        ///IF OBJECT_ID(&apos;vwSearches&apos;,&apos;v&apos;) IS NOT NULL
        ///BEGIN
        ///DROP VIEW vwSearches
        ///END
        ///GO
        ///
        ///CREATE VIEW vwSearches
        ///AS
        ///SELECT searches.id, searches.session_id, search_terms.search_term, users.id as &apos;User_ID&apos;
        ///FROM searc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_vwSearches {
            get {
                return ResourceManager.GetString("View_vwSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- ============================================
        ///-- Author: Glenn Pepper
        ///-- Create Date: 04/12/2019
        ///-- Version: 1.0
        ///-- Description: This view displays session information
        ///-- =============================================
        ///
        ///
        ///IF OBJECT_ID(&apos;vwSessions&apos;,&apos;v&apos;) IS NOT NULL
        ///BEGIN
        ///DROP VIEW vwSessions
        ///END
        ///GO
        ///CREATE VIEW vwSessions AS
        ///
        ///WITH CTE AS 
        ///(SELECT 
        ///	s.id
        ///	,ai_session_id
        ///	-- ENTRANCE
        ///	,(
        ///		select top 1 h.id		-- ID
        ///		from hits h
        ///		where h.session_id = s.id
        ///		order by [hit_timestamp] asc        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View_vwSessions {
            get {
                return ResourceManager.GetString("View_vwSessions", resourceCulture);
            }
        }
    }
}
