//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CreationTime&quot;: &quot;2018-07-02T14:52:57&quot;,
        ///    &quot;Id&quot;: &quot;1c0655f1-e870-401b-949c-398cb9a8f984&quot;,
        ///    &quot;Operation&quot;: &quot;UserLoggedIn&quot;,
        ///    &quot;OrganizationId&quot;: &quot;d38e0d78-3edc-4124-8483-6f8aad3bc32a&quot;,
        ///    &quot;RecordType&quot;: 15,
        ///    &quot;ResultStatus&quot;: &quot;Succeeded&quot;,
        ///    &quot;UserKey&quot;: &quot;1003BFFD9A7D358F@domainredacted.com&quot;,
        ///    &quot;UserType&quot;: 0,
        ///    &quot;Version&quot;: 1,
        ///    &quot;Workload&quot;: &quot;AzureActiveDirectory&quot;,
        ///    &quot;ClientIP&quot;: &quot;31.168.15.90&quot;,
        ///    &quot;ObjectId&quot;: &quot;Unknown&quot;,
        ///    &quot;UserId&quot;: &quot;motim@domainredacted.com&quot;,
        ///    &quot;AzureActive [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityAzure_AD_Login {
            get {
                return ResourceManager.GetString("ActivityAzure_AD_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CreationTime&quot;: &quot;2018-07-10T12:06:50&quot;,
        ///    &quot;Id&quot;: &quot;09a84061-2c80-4850-b709-08d5e65d9e73&quot;,
        ///    &quot;Operation&quot;: &quot;New-MigrationBatch&quot;,
        ///    &quot;OrganizationId&quot;: &quot;d38e0d78-3edc-4124-8483-6f8aad3bc32a&quot;,
        ///    &quot;RecordType&quot;: 1,
        ///    &quot;ResultStatus&quot;: &quot;True&quot;,
        ///    &quot;UserKey&quot;: &quot;1003BFFD9A7D3BD6&quot;,
        ///    &quot;UserType&quot;: 2,
        ///    &quot;Version&quot;: 1,
        ///    &quot;Workload&quot;: &quot;Exchange&quot;,
        ///    &quot;ClientIP&quot;: &quot;127.0.137.131:40927&quot;,
        ///    &quot;ObjectId&quot;: &quot;&quot;,
        ///    &quot;UserId&quot;: &quot;tamaraa@testtenant.local&quot;,
        ///    &quot;ExternalAccess&quot;: false,
        ///    &quot;Organization [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityExchange {
            get {
                return ResourceManager.GetString("ActivityExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CreationTime&quot;: &quot;2018-04-10T05:19:01&quot;,
        ///    &quot;Id&quot;: &quot;16124be1-d537-4f99-bdbc-08d59ea2924e&quot;,
        ///    &quot;Operation&quot;: &quot;SharingSet&quot;,
        ///    &quot;OrganizationId&quot;: &quot;e307563d-5fcd-4e12-a554-9927f388b1cf&quot;,
        ///    &quot;RecordType&quot;: 14,
        ///    &quot;UserKey&quot;: &quot;i:0h.f|membership|10030000974e5923@live.com&quot;,
        ///    &quot;UserType&quot;: 0,
        ///    &quot;Version&quot;: 1,
        ///    &quot;Workload&quot;: &quot;SharePoint&quot;,
        ///    &quot;ClientIP&quot;: &quot;213.52.202.3&quot;,
        ///    &quot;ObjectId&quot;: &quot;https://sometenant.sharepoint.com/teams/secure-52253/JL 1/Dokumenttien versionhallinta.docx&quot;,
        ///    &quot;UserId&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitySharePoint_Permission_Change {
            get {
                return ResourceManager.GetString("ActivitySharePoint_Permission_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CreationTime&quot;: &quot;2018-04-25T15:07:19&quot;,
        ///    &quot;Id&quot;: &quot;a49e968b-cd96-44ac-6ea9-08d5aabe3dba&quot;,
        ///    &quot;Operation&quot;: &quot;FilePreviewed&quot;,
        ///    &quot;OrganizationId&quot;: &quot;34eb3720-3d40-4da8-9f80-f939e220821c&quot;,
        ///    &quot;RecordType&quot;: 6,
        ///    &quot;UserKey&quot;: &quot;i:0h.f|membership|10037ffea94e7503@live.com&quot;,
        ///    &quot;UserType&quot;: 0,
        ///    &quot;Version&quot;: 1,
        ///    &quot;Workload&quot;: &quot;SharePoint&quot;,
        ///    &quot;ClientIP&quot;: &quot;52.109.28.19&quot;,
        ///    &quot;ObjectId&quot;: &quot;https://m365x246423.sharepoint.com/Shared Documents/CAS/Marketing Strategy Future.docx&quot;,
        ///    &quot;UserId&quot;: &quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivitySharePoint_Various_Responses {
            get {
                return ResourceManager.GetString("ActivitySharePoint_Various_Responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;CreationTime&quot;: &quot;2018-11-22T13:02:42&quot;,
        ///    &quot;Id&quot;: &quot;c1a108ee-778a-4b3f-98b1-780163ee8c4a&quot;,
        ///    &quot;Operation&quot;: &quot;TeamsSessionStarted&quot;,
        ///    &quot;OrganizationId&quot;: &quot;00000-5953-484b-ae95-000000&quot;,
        ///    &quot;RecordType&quot;: 25,
        ///    &quot;UserKey&quot;: &quot;aaaa-1b7b-0000-90c1-fffff&quot;,
        ///    &quot;UserType&quot;: 0,
        ///    &quot;Version&quot;: 1,
        ///    &quot;Workload&quot;: &quot;MicrosoftTeams&quot;,
        ///    &quot;ObjectId&quot;: &quot;Web (1415\/1.0.0.2018110740)&quot;,
        ///    &quot;UserId&quot;: &quot;user@domain.com&quot;,
        ///    &quot;ExtraProperties&quot;: [
        ///      {
        ///        &quot;Key&quot;: &quot;OriginEnvironment&quot;,
        ///        &quot;Value&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityTeams {
            get {
                return ResourceManager.GetString("ActivityTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;view&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;Page Name&quot;,
        ///            &quot;count&quot;: 1,
        ///            &quot;durationMetric&quot;: {
        ///                &quot;value&quot;: 0.0,
        ///                &quot;count&quot;: 1.0,
        ///                &quot;min&quot;: 0.0,
        ///                &quot;max&quot;: 0.0,
        ///                &quot;stdDev&quot;: 0.0,
        ///                &quot;sampledValue&quot;: 0.0
        ///            },
        ///            &quot;url&quot;: &quot;https://sharepoint/whatever&quot;,
        ///            &quot;urlData&quot;: {
        ///                &quot;base&quot;: &quot;/whatever&quot;,
        ///                &quot;host&quot;: &quot;sharepoint&quot;,
        ///                &quot;hashTag&quot;: &quot;#&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Anon_PageView_JSon {
            get {
                return ResourceManager.GetString("Anon_PageView_JSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;view&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;SPO Insights Modern - Home&quot;,
        ///      &quot;count&quot;: 1,
        ///      &quot;durationMetric&quot;: {
        ///        &quot;value&quot;: 24170000.0,
        ///        &quot;count&quot;: 1.0,
        ///        &quot;min&quot;: 24170000.0,
        ///        &quot;max&quot;: 24170000.0,
        ///        &quot;stdDev&quot;: 0.0,
        ///        &quot;sampledValue&quot;: 24170000.0
        ///      },
        ///      &quot;url&quot;: &quot;https://m365x246423.sharepoint.com/sites/SPOInsightsModern&quot;,
        ///      &quot;urlData&quot;: {
        ///        &quot;base&quot;: &quot;/sites/SPOInsightsModern&quot;,
        ///        &quot;host&quot;: &quot;m365x246423.sharepoint.com&quot;,
        ///        &quot;hashTag&quot;: &quot;&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitDateTimePrecisionTestData {
            get {
                return ResourceManager.GetString("HitDateTimePrecisionTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;UserSearch&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;f5e63451-e6af-11e8-99cf-a9c3aabd7bef&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-12T19:20:03.734Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 66.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;77RX1&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitOversizedSearchEvent {
            get {
                return ResourceManager.GetString("HitOversizedSearchEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;view&quot;:[{&quot;name&quot;:&quot;Add a page&quot;,&quot;count&quot;:1,&quot;durationMetric&quot;:{&quot;value&quot;:32860000.0,&quot;count&quot;:1.0,&quot;min&quot;:32860000.0,&quot;max&quot;:32860000.0,&quot;stdDev&quot;:0.0,&quot;sampledValue&quot;:32860000.0},&quot;url&quot;:&quot;https://m365x246423.sharepoint.com/sites/spoinsights/_layouts/15/CreatePublishingPageDialog.aspx?IsDlg=1&quot;,&quot;urlData&quot;:{&quot;base&quot;:&quot;/sites/spoinsights/_layouts/15/CreatePublishingPageDialog.aspx&quot;,&quot;host&quot;:&quot;m365x246423.sharepoint.com&quot;,&quot;hashTag&quot;:&quot;&quot;,&quot;protocol&quot;:&quot;https&quot;}}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;af82e6d1-48a7-11e8-9093-71e48ff26ad9&quot;,&quot;documentVersion&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitOversizedSearchEvent_Hit {
            get {
                return ResourceManager.GetString("HitOversizedSearchEvent_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;PAGE_EXIT&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;b5ce88f0-48a7-11e8-9093-71e48ff26ad9&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-04-25T16:42:55.483Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 66.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;CN0D6&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitPage_Exit_Event_json {
            get {
                return ResourceManager.GetString("HitPage_Exit_Event_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;view&quot;:[{&quot;name&quot;:&quot;Add a page&quot;,&quot;count&quot;:1,&quot;durationMetric&quot;:{&quot;value&quot;:32860000.0,&quot;count&quot;:1.0,&quot;min&quot;:32860000.0,&quot;max&quot;:32860000.0,&quot;stdDev&quot;:0.0,&quot;sampledValue&quot;:32860000.0},&quot;url&quot;:&quot;https://m365x246423.sharepoint.com/sites/spoinsights/_layouts/15/CreatePublishingPageDialog.aspx?IsDlg=1&quot;,&quot;urlData&quot;:{&quot;base&quot;:&quot;/sites/spoinsights/_layouts/15/CreatePublishingPageDialog.aspx&quot;,&quot;host&quot;:&quot;m365x246423.sharepoint.com&quot;,&quot;hashTag&quot;:&quot;&quot;,&quot;protocol&quot;:&quot;https&quot;}}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;af82e6d1-48a7-11e8-9093-71e48ff26ad9&quot;,&quot;documentVersion&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitPageView_Export_json {
            get {
                return ResourceManager.GetString("HitPageView_Export_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;UserSearch&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;aaf4f4f1-e8f2-11e8-821f-cd539370fbd6&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-15T16:22:38.597Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 70.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;/HaHD&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_3___New_SessionID___Events {
            get {
                return ResourceManager.GetString("HitTest_3___New_SessionID___Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;view&quot;:[{&quot;name&quot;:&quot;SPO Insights Modern - Home&quot;,&quot;count&quot;:1,&quot;durationMetric&quot;:{&quot;value&quot;:15070000.0,&quot;count&quot;:1.0,&quot;min&quot;:15070000.0,&quot;max&quot;:15070000.0,&quot;stdDev&quot;:0.0,&quot;sampledValue&quot;:15070000.0},&quot;url&quot;:&quot;https://m365x246423.sharepoint.com/sites/spoinsightsmodern&quot;,&quot;urlData&quot;:{&quot;base&quot;:&quot;/sites/spoinsightsmodern&quot;,&quot;host&quot;:&quot;m365x246423.sharepoint.com&quot;,&quot;hashTag&quot;:&quot;&quot;,&quot;protocol&quot;:&quot;https&quot;}}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;997d1041-e8f2-11e8-88a2-81489c95ed9c&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-15T16:22:08.938Z&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_3___New_SessionID___PageViews {
            get {
                return ResourceManager.GetString("HitTest_3___New_SessionID___PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;UserSearch&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;f5e63451-e6af-11e8-99cf-a9c3aabd7bef&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-12T19:20:03.734Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 66.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;77RX1&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_Journey_1_Events {
            get {
                return ResourceManager.GetString("HitTest_Journey_1_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  &quot;view&quot;: [    {      &quot;name&quot;: &quot;Page 1&quot;,      &quot;count&quot;: 1,      &quot;durationMetric&quot;: {        &quot;value&quot;: 0.0,        &quot;count&quot;: 1.0,        &quot;min&quot;: 0.0,        &quot;max&quot;: 0.0,        &quot;stdDev&quot;: 0.0,        &quot;sampledValue&quot;: 0.0      },      &quot;url&quot;: &quot;https://m365x246423.sharepoint.com/sites/SPOInsightsModern/SitePages/Page-1.aspx&quot;,      &quot;urlData&quot;: {        &quot;base&quot;: &quot;/sites/SPOInsightsModern/SitePages/Page-1.aspx&quot;,        &quot;host&quot;: &quot;m365x246423.sharepoint.com&quot;,        &quot;hashTag&quot;: &quot;&quot;,        &quot;protocol&quot;: &quot;https&quot;      }    }  ],  &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_Journey_1_PageViews {
            get {
                return ResourceManager.GetString("HitTest_Journey_1_PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;PAGE_EXIT&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;9b5ceb40-e8db-11e8-9f75-1d471caaf4b3&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-15T13:37:33.873Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 70.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;LYnm4&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_Journey_2_Events {
            get {
                return ResourceManager.GetString("HitTest_Journey_2_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;view&quot;:[{&quot;name&quot;:&quot;SPO Insights Modern - Home&quot;,&quot;count&quot;:1,&quot;durationMetric&quot;:{&quot;value&quot;:16670000.0,&quot;count&quot;:1.0,&quot;min&quot;:16670000.0,&quot;max&quot;:16670000.0,&quot;stdDev&quot;:0.0,&quot;sampledValue&quot;:16670000.0},&quot;url&quot;:&quot;https://m365x246423.sharepoint.com/sites/spoinsightsmodern&quot;,&quot;urlData&quot;:{&quot;base&quot;:&quot;/sites/spoinsightsmodern&quot;,&quot;host&quot;:&quot;m365x246423.sharepoint.com&quot;,&quot;hashTag&quot;:&quot;&quot;,&quot;protocol&quot;:&quot;https&quot;}}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;8bd034c0-e8db-11e8-abe7-9b2a07cfa9bc&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2018-11-15T13:37:06.711Z&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitTest_Journey_2_PageViews {
            get {
                return ResourceManager.GetString("HitTest_Journey_2_PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;listTitle&quot;: &quot;Pages&quot;,
        ///  &quot;pageItemId&quot;: &quot;2&quot;,
        ///  &quot;props&quot;: &quot;{\&quot;__metadata\&quot;:{\&quot;id\&quot;:\&quot;c602fe15-f56b-4c63-bbb4-5c693894ea90\&quot;,\&quot;uri\&quot;:\&quot;https://m365x72460609.sharepoint.com/sites/Classic/_api/Web/Lists(guid&apos;aa85bd92-eb6b-4b91-90ed-10485dff0d9b&apos;)/Items(2)\&quot;,\&quot;etag\&quot;:\&quot;\\\&quot;3\\\&quot;\&quot;,\&quot;type\&quot;:\&quot;SP.Data.PagesItem\&quot;},\&quot;FirstUniqueAncestorSecurableObject\&quot;:{\&quot;__deferred\&quot;:{\&quot;uri\&quot;:\&quot;https://m365x72460609.sharepoint.com/sites/Classic/_api/Web/Lists(guid&apos;aa85bd92-eb6b-4b91-90ed-10485dff0d9b&apos;)/Items(2)/FirstUniqueAnc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageUpdateEventAppInsightsQueryResult {
            get {
                return ResourceManager.GetString("PageUpdateEventAppInsightsQueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;publishData&gt;
        ///
        ///    &lt;publishProfile profileName=&quot;o365analyticsdemocopy - FTP&quot; publishMethod=&quot;FTP&quot;
        ///        publishUrl=&quot;ftp://server/site/wwwroot&quot; ftpPassiveMode=&quot;True&quot;
        ///        userName=&quot;username&quot;
        ///        userPWD=&quot;asdf&quot;
        ///        destinationAppUrl=&quot;https://o365analyticsdemocopy.azurewebsites.net&quot;
        ///        SQLServerDBConnectionString=&quot;SQL&quot;
        ///        mySQLDBConnectionString=&quot;&quot; hostingProviderForumLink=&quot;&quot; controlPanelLink=&quot;http://windows.azure.com&quot;
        ///        webSystem=&quot;WebSites&quot; targetDatabaseEngineType=&quot;sqlazu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishXml {
            get {
                return ResourceManager.GetString("PublishXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;event&quot;:[{&quot;name&quot;:&quot;UserSearch&quot;,&quot;count&quot;:1}],&quot;internal&quot;:{&quot;data&quot;:{&quot;id&quot;:&quot;639d60e1-6c07-11e9-9df5-f3579f5a1f3e&quot;,&quot;documentVersion&quot;:&quot;1.61&quot;}},&quot;context&quot;:{&quot;data&quot;:{&quot;eventTime&quot;:&quot;2019-05-01T11:51:01.249Z&quot;,&quot;isSynthetic&quot;:false,&quot;samplingRate&quot;:100.0},&quot;device&quot;:{&quot;id&quot;:&quot;browser&quot;,&quot;type&quot;:&quot;Browser&quot;,&quot;osVersion&quot;:&quot;Windows 10&quot;,&quot;deviceName&quot;:&quot;Other&quot;,&quot;deviceModel&quot;:&quot;Other&quot;,&quot;browser&quot;:&quot;Chrome&quot;,&quot;browserVersion&quot;:&quot;Chrome 72.0&quot;,&quot;screenResolution&quot;:{}},&quot;user&quot;:{&quot;anonId&quot;:&quot;wsAGx&quot;,&quot;authId&quot;:&quot;admin@m365x246423.onmicrosoft.com&quot;,&quot;isAuthenticated&quot;:true},&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string searches {
            get {
                return ResourceManager.GetString("searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;__metadata\&quot;:{\&quot;id\&quot;:\&quot;c602fe15-f56b-4c63-bbb4-5c693894ea90\&quot;,\&quot;uri\&quot;:\&quot;https://m365x72460609.sharepoint.com/sites/Classic/_api/Web/Lists(guid&apos;aa85bd92-eb6b-4b91-90ed-10485dff0d9b&apos;)/Items(2)\&quot;,\&quot;etag\&quot;:\&quot;\\\&quot;3\\\&quot;\&quot;,\&quot;type\&quot;:\&quot;SP.Data.PagesItem\&quot;},\&quot;FirstUniqueAncestorSecurableObject\&quot;:{\&quot;__deferred\&quot;:{\&quot;uri\&quot;:\&quot;https://m365x72460609.sharepoint.com/sites/Classic/_api/Web/Lists(guid&apos;aa85bd92-eb6b-4b91-90ed-10485dff0d9b&apos;)/Items(2)/FirstUniqueAncestorSecurableObject\&quot;}},\&quot;RoleAssignments\&quot;:{\&quot;__deferred\&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringifiedJson {
            get {
                return ResourceManager.GetString("StringifiedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@odata.context&quot;: &quot;https://graph.microsoft.com/beta/$metadata#communications/callRecords(sessions(segments()))/$entity&quot;,
        ///  &quot;id&quot;: &quot;e7783616-3f5f-48c8-bd64-f6038442cd47&quot;,
        ///  &quot;version&quot;: 2,
        ///  &quot;type&quot;: &quot;groupCall&quot;,
        ///  &quot;modalities&quot;: [
        ///    &quot;audio&quot;,
        ///    &quot;videoBasedScreenSharing&quot;,
        ///    &quot;screenSharing&quot;
        ///  ],
        ///  &quot;lastModifiedDateTime&quot;: &quot;2020-10-06T12:52:54.1608693Z&quot;,
        ///  &quot;startDateTime&quot;: &quot;2020-10-06T12:30:39.1943225Z&quot;,
        ///  &quot;endDateTime&quot;: &quot;2020-10-06T12:35:45.7708215Z&quot;,
        ///  &quot;joinWebUrl&quot;: null,
        ///  &quot;organizer&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsCall_3way {
            get {
                return ResourceManager.GetString("TeamsCall_3way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.context&quot;: &quot;https://graph.microsoft.com/beta/$metadata#communications/callRecords(sessions(segments()))/$entity&quot;,
        ///    &quot;id&quot;: &quot;ccf29131-4011-4ef6-978c-402232c235c9&quot;,
        ///    &quot;version&quot;: 1,
        ///    &quot;type&quot;: &quot;groupCall&quot;,
        ///    &quot;modalities&quot;: [
        ///        &quot;audio&quot;
        ///    ],
        ///    &quot;lastModifiedDateTime&quot;: &quot;2020-10-06T11:42:47.7117121Z&quot;,
        ///    &quot;startDateTime&quot;: &quot;2020-10-06T11:32:49.7639581Z&quot;,
        ///    &quot;endDateTime&quot;: &quot;2020-10-06T11:32:51.904649Z&quot;,
        ///    &quot;joinWebUrl&quot;: &quot;https://teams.microsoft.com/l/meetup-join/19%3ac106df53f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsCall_Failed_Call {
            get {
                return ResourceManager.GetString("TeamsCall_Failed_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;@odata.context&quot;: &quot;https://graph.microsoft.com/beta/$metadata#communications/callRecords(sessions(segments()))/$entity&quot;,
        ///    &quot;id&quot;: &quot;8952c843-755c-4a1e-8e98-3acf05924f57&quot;,
        ///    &quot;version&quot;: 2,
        ///    &quot;type&quot;: &quot;peerToPeer&quot;,
        ///    &quot;modalities&quot;: [
        ///        &quot;audio&quot;,
        ///        &quot;screenSharing&quot;
        ///    ],
        ///    &quot;lastModifiedDateTime&quot;: &quot;2020-10-08T08:14:09.78271Z&quot;,
        ///    &quot;startDateTime&quot;: &quot;2020-10-08T08:00:54.627227Z&quot;,
        ///    &quot;endDateTime&quot;: &quot;2020-10-08T08:01:19.1161293Z&quot;,
        ///    &quot;joinWebUrl&quot;: null,
        ///    &quot;organizer&quot;: {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamsCall_Peer2PeerCall {
            get {
                return ResourceManager.GetString("TeamsCall_Peer2PeerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;EnvironmentType&quot;: 0,
        ///  &quot;LocalSourceOverride&quot;: {
        ///    &quot;Components&quot;: {
        ///      &quot;AITracker&quot;: {
        ///        &quot;FileLocation&quot;: &quot;C:\\Users\\sambetts\\Desktop\\dev - build 1190\\AITrackerInstaller.zip&quot;
        ///      },
        ///      &quot;WebJobActivity&quot;: {
        ///        &quot;FileLocation&quot;: &quot;C:\\Users\\sambetts\\Desktop\\dev - build 1190\\Office365ActivityImporter.zip&quot;
        ///      },
        ///      &quot;WebJobAppInsights&quot;: {
        ///        &quot;FileLocation&quot;: &quot;C:\\Users\\sambetts\\Desktop\\dev - build 1190\\AppInsightsImporter.zip&quot;
        ///      },
        ///      &quot;ControlPanel&quot;: {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestInstallerConfig {
            get {
                return ResourceManager.GetString("TestInstallerConfig", resourceCulture);
            }
        }
    }
}
