name: ci

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      publish-files:
        description: Should files be published as a release?
        type: boolean
        default: false
        required: false

# Original
# Preparation:
#   - Get signing certificate
#   - Transform configuration files
#   - Restore dependencies
# Build:
#   - Build .Net projects
#   - Build AI Tracker
# Test:
#   - Run test suite
# Output:
#   - Clean .Net builds
#   - Clean AI Tracker
#   - Copy PS scripts
#   - Zip files
#   - Publish artifacts

# * dotnet projects and AI Tracker can be paralellized

jobs:
  # Tests job
  # Preparation:
  #   - Transform configuration files
  #   - Restore dependencies
  # Build:
  #   - Build .Net projects
  # Test:
  #   - Run test suite
  unit_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release] # [Debug, Release]
    env:
      Solution_Name: Tests.UnitTests.csproj
      Solution_Directory: src\AnalyticsEngine\Tests.UnitTests
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      # - name: Decode the pfx
      #   run: |
      #     $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
      #     $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath SPOInsightsBinaries.pfx
      #     [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      - name: Restore the application
        run: msbuild $env:Solution_Directory /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Build
        run: msbuild $env:Solution_Directory /p:Configuration=$env:Configuration
        #/p:PackageCertificateKeyFile=SPOInsightsBinaries.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
        env:
          Configuration: ${{ matrix.configuration }}
      # Execute all unit tests in the solution
      - name: Execute unit tests
        uses: microsoft/vstest-action@v1.0.0 # https://github.com/microsoft/vstest-action
        with:
          testAssembly: Tests.UnitTests.dll
          searchFolder: $env:Solution_Directory\bin\$env:Configuration\
          runInParallel: true
        env:
          Configuration: ${{ matrix.configuration }}
        # Remove the pfx
      # - name: Remove the pfx
      #   run: Remove-Item -Path SPOInsightsBinaries.pfx
      
# Preparation:
#   - Get signing certificate
#   - Transform configuration files
#   - Restore dependencies
# Build:
#   - Build .Net projects
# Test:
#   - Run test suite
# Output:
#   - Clean .Net builds
#   - Clean AI Tracker
#   - Copy PS scripts
#   - Zip files
#   - Publish artifacts

# NPM ai tracker
# Test:
#   - Build AI Tracker
# Output:
#   - Clean AI Tracker
#   - Zip files
#   - Publish artifacts
