name: pr

on:
  pull_request:
    types:
      - ready_for_review
  workflow_dispatch:
    inputs:
      force_build:
        default: false
        required: false
        type: boolean
        description: Bypass code changed check

env:
  Solution_Directory: src\AnalyticsEngine\
  Build_Platform: Any CPU
  Build_ProcessorArchitecture: x86
  ClientID: ${{ secrets.APP_CLIENTID }}
  ClientSecret: ${{ secrets.APP_CLIENTSECRET }}
  TenantGUID: ${{ secrets.APP_TENANTGUID }}
  TenantDomain: ${{ secrets.APP_TENANTDOMAIN }}
  CognitiveEndpoint: ${{ secrets.APP_COGNITIVEENDPOINT }}
  CognitiveKey: ${{ secrets.APP_COGNITIVEKEY}}
  CosmosDbTestContainerCurrent: stats
  CosmosDbTestContainerHistory: history
  CosmosDbTestDatabaseName: UnitTestDevOps
  CosmosDb: ${{ secrets.APP_COSMOSDB }}
  redis: ${{ secrets.CONNECTIONSTRINGS_REDIS }}
  ServiceBus: ${{ secrets.CONNECTIONSTRINGS_SERVICEBUS }}
  Storage: ${{ secrets.CONNECTIONSTRINGS_STORAGE }}
  SoftwareDownloadURL: ${{ secrets.SOFTWAREDOWNLOADURL }}
  StatsApiSecret: ${{ secrets.STATSAPISECRET }}
  StatsApiUrl: ${{ secrets.STATSAPIURL }}

jobs:
  setup_build:
    # This step will calculate the build number with an offset
    # so that build numbers will follow the ones from Azure DevOps.
    # It will also check that the important folders have been updated.
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ inputs.force_build || steps.changes.outputs.code == 'true' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Check if code has been modified so a build is needed
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - 'src/**'
              - 'reports/**'

  build_dotnet:
    # Preparation:
    #   - Transform configuration files
    #   - Restore dependencies
    # Build:
    #   - Build .Net projects
    # Output:
    #   - Clean .Net builds
    #   - Copy PS scripts
    #   - Zip files
    #   - Publish artifacts
    runs-on: windows-latest
    needs: setup_build
    if: needs.setup_build.outputs.code_changed == 'true'
    strategy:
      matrix:
        configuration: [Release] # [Debug, Release]
    env:
      BuildId: ${{ github.run_number }}
      BuildLabel: PR ${{ github.run_number }}
    steps:
      - name: Prepare build
        id: prep
        shell: bash
        run: |
          mkdir -p "${{ env.Zips_Folder }}"
          echo "ZIPS_FOLDER=${{ env.Zips_Folder }}" >> "$GITHUB_OUTPUT"
        env:
          Zips_Folder: ${{ runner.temp }}/zips/
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Cache NuGet Packages
        id: nuget-packages
        uses: actions/cache@v4
        env:
          cache-name: nuget-package-cache
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-${{ env.cache-name }}
      # Configuration files
      - name: Year substitution
        shell: bash
        run: |
          year=$(date +%Y)
          find ./src -name AssemblyInfo.cs | xargs sed -i "s/© __year__/© $year/"
      - name: Config substitutions
        uses: devops-actions/variable-substitution@v1.2
        with:
          files: '${{ env.Solution_Directory }}\*\App.Release.config, ${{ env.Solution_Directory }}\Web\Web.Release.config'
      - name: Restore the application
        run: msbuild ${{ env.Solution_Directory }} -t:Restore `
          -p:Configuration=${{ env.Configuration }} `
          -p:Platform="${{ env.Build_Platform }}" `
          -p:ProcessorArchitecture=${{ env.Build_ProcessorArchitecture }}
        env:
          Configuration: ${{ matrix.configuration }}
      # Projects building
      - name: Build WebJob.AppInsightsImporter
        run: msbuild ${{ env.Solution_Directory }}\WebJob.AppInsightsImporter\WebJob.AppInsightsImporter.csproj `
          -p:Configuration=${{ env.Configuration }} `
          -p:Platform="${{ env.Build_Platform }}" `
          -p:ProcessorArchitecture=${{ env.Build_ProcessorArchitecture }} `
          -p:OutDir=${{ runner.temp }}\AppInsightsImporter `
          -p:OutputPath=${{ env.Configuration }} `
          -p:AllowedReferenceRelatedFileExtensions=none `
          -p:EmitCompilerGeneratedFiles=false
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Archive AppInsightsImporter
        run: |
          Remove-Item -Force -Recurse -ErrorAction SilentlyContinue "${{ runner.temp }}\AppInsightsImporter\_PublishedWebsites"
          Compress-Archive -Force -Path "${{ runner.temp }}\AppInsightsImporter" `
          -DestinationPath "${{ env.folder }}\AppInsightsImporter.zip"
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
      - name: Build WebJob.Office365ActivityImporter
        run: |
          msbuild ${{ env.Solution_Directory }}\WebJob.Office365ActivityImporter\WebJob.Office365ActivityImporter.csproj `
          -p:Configuration=${{ env.Configuration }} `
          -p:Platform="${{ env.Build_Platform }}" `
          -p:ProcessorArchitecture=${{ env.Build_ProcessorArchitecture }} `
          -p:OutDir=${{ runner.temp }}\Office365ActivityImporter `
          -p:OutputPath=${{ env.Configuration }} `
          -p:AllowedReferenceRelatedFileExtensions=none `
          -p:EmitCompilerGeneratedFiles=false
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Copy Automation scripts
        run: |
          Copy-Item -Verbose -Force -Recurse `
          -Path "src/AnalyticsEngine/WebJob.Office365ActivityImporter/AutomationPS" `
          -Destination "${{ runner.temp }}\Office365ActivityImporter\"
      - name: Archive Office365ActivityImporter
        run: |
          Remove-Item -Force -Recurse -ErrorAction SilentlyContinue `
          "${{ runner.temp }}\Office365ActivityImporter\_PublishedWebsites"
          Compress-Archive -Force -Path "${{ runner.temp }}\Office365ActivityImporter" `
          -DestinationPath "${{ env.folder }}\Office365ActivityImporter.zip"
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
      - name: Build Website
        run: msbuild ${{ env.Solution_Directory }}\Web\Web.csproj `
          -p:Configuration=${{ env.Configuration }} `
          -p:Platform="${{ env.Build_Platform }}" `
          -p:ProcessorArchitecture=${{ env.Build_ProcessorArchitecture }} `
          -p:OutDir=${{ runner.temp }}\Website `
          -p:OutputPath=${{ env.Configuration }} `
          -p:AllowedReferenceRelatedFileExtensions=none `
          -p:EmitCompilerGeneratedFiles=false
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Archive Website
        run: |
          Remove-Item -Force -Recurse -ErrorAction SilentlyContinue `
          "${{ runner.temp }}\Website\_PublishedWebsites\Web\bin\Scripts"
          Compress-Archive -Force -Path "${{ runner.temp }}\Website\_PublishedWebsites\Web" `
          -DestinationPath "${{ env.folder }}\Website.zip"
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
      - name: Build Installer
        run: |
          msbuild ${{ env.Solution_Directory }}\App.ControlPanel\App.ControlPanel.WinForms.csproj `
          -p:Configuration=${{ env.Configuration }} `
          -p:Platform="${{ env.Build_Platform }}" `
          -p:ProcessorArchitecture=${{ env.Build_ProcessorArchitecture }} `
          -p:OutDir=${{ runner.temp }}\ControlPanelApp `
          -p:OutputPath=${{ env.Configuration }} `
          -p:AllowedReferenceRelatedFileExtensions=none `
          -p:EmitCompilerGeneratedFiles=false
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Archive ControlPanelApp
        run: Compress-Archive -Force -Path "${{ runner.temp }}\ControlPanelApp" `
          -DestinationPath "${{ env.folder }}\ControlPanelApp.zip"
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
      - name: Archive Reports
        run: |
          Get-ChildItem '.\reports\Usage Analytics\*' `
          -Exclude "*_base.pbit" -Include "*.pbit","Readme.txt" | Compress-Archive `
          -Force -DestinationPath "${{ env.folder }}\Analytics_Reports.zip"
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
      # Wrap up
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.folder }}
          name: drop_dotnet
          if-no-files-found: error
        env:
          folder: ${{ steps.prep.outputs.ZIPS_FOLDER }}
  
  build_aitracker:
    # NPM ai tracker
    # Build:
    #   - Build AI Tracker
    # Output:
    #   - Clean AI Tracker
    #   - Zip files
    #   - Publish artifacts
    runs-on: ubuntu-latest
    needs: setup_build
    if: needs.setup_build.outputs.code_changed == 'true'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build AITracker
        run: |
          cd src/SPO/AITracker/TypeScript
          npm ci
          npm run build
          cd ../..
          rm -rf AITracker/TypeScript
          zip -r AITrackerInstaller.zip AITracker
      # Wrap up
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: src/SPO/AITrackerInstaller.zip
          name: drop_aitracker
          if-no-files-found: error
